# https://www.playframework.com/documentation/latest/Configuration
play.modules.enabled += "play.api.db.slick.SlickModule"

# Database configuration
db.default.driver = "com.mysql.cj.jdbc.Driver"
db.default.url = "jdbc:mysql://localhost:3306/beersdb?useSSL=false&serverTimezone=UTC"
db.default.username = "beersuser"
db.default.password = "Rooney98@"

# Slick configuration
slick.dbs.default.profile = "slick.jdbc.MySQLProfile$"
slick.dbs.default.db.driver = "com.mysql.cj.jdbc.Driver"
slick.dbs.default.db.url = "jdbc:mysql://localhost:3306/beersdb?useSSL=false&serverTimezone=UTC"
slick.dbs.default.db.user = "beersuser"
slick.dbs.default.db.password = "Rooney98@"

# Evolutions configuration
play.evolutions.enabled = true
play.evolutions.autoApply = true

# Enable the CORS filter
play.filters.enabled += "play.filters.cors.CORSFilter"

# Configure CORS settings
play.filters.cors {
  allowedOrigins = ["http://localhost:5173"]
  allowedHttpMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowedHttpHeaders = ["Accept", "Content-Type", "Origin", "Authorization"]
  preflightMaxAge = 1h
}

